baseURL = "/"
languageCode = "ko-kr"
title = "IV"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "dark"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[params.assets]
  favicon = "/img/favicon.ico"
  favicon16x16 = "/img/favicon-16x16.png"
  favicon32x32 = "/img/favicon-32x32.png"
  apple_touch_icon = "/img/apple-touch-icon.png"
  safari_pinned_tab = "/img/safari-pinned-tab.svg"

  [params.search]
    enabled = true
    placeholder = "검색…"
    

[permalinks]
  notes = "/:contentbasename/"

# ✅ PaperMod 검색용 JSON은 home(홈)에서만 생성
[outputs]
  home = ["HTML", "RSS", "JSON"]
  # section = ["HTML", "RSS"]  # ← 굳이 필요 없으면 아예 제거

# ✅ Raw HTML(<details> 등) 허용
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# (선택) 경고 끄기
# ignoreLogs = ['warning-goldmark-raw-html']
